# exception_homework_3